### ISSUE TITLE
Queries have a character limit on windows

### ISSUE THREAD

**Issue by jmsfltchr** [vaticle/typedb-console#133]
## Description

Using either the default command prompt, and using power shell, I have seen that when users try to write long queries they hit a character limit. At some point the prompt stops accepting new characters.

## Workaround

The same limit does not apply when pasting a query into the console from elsewhere, so the workaround is to write long queries in any IDE and paste them into the console instead.

**Comment by vmax** [comment]
@jmsfltchr would it be possible for you to provide a sample query that's too long to be typed? Also, if you have a Windows machine around, could you obtain [Windows Terminal](https://github.com/microsoft/terminal) and test it there?

**Comment by jmsfltchr** [comment]
@vmax this was too long:
```
insert $o isa organisation, has name "facebook", has registration-number "002"; $p isa person, has full-name "Frodo Baggins", has email "frodo@facebook.com"; $pr isa profession, has title "Ringbearer"; $emp(employer: $o, employee: $p, job: $pr) isa employment, has reference-id "r-200";
```
I shall try and fish out a windows machine!

**Comment by jamesreprise** [comment]
This issue seems to be resolved, the given long query is accepted when typed manually into TypeDB Console 2.14.2.
