### ISSUE TITLE
List rules from within console

### ISSUE THREAD

**Issue by flyingsilverfin** [vaticle/typedb-console#141]
Because rules are no longer concepts, we cannot query for them using Graql. However, it is very useful to be able to list all rules, which allows us to then undefine rules by name.

The transaction API that exposes this information is `LogicManager.all()` - we should allow this to be called from console in a transaction.

Workaround:
* run the schema exporter: `./grakn server schema [database-name]` which will also dump the existing rules

**Comment by haikalpribadi** [comment]
@flyingsilverfin you can't do `./grakn server schema` anymore on `master`. The database schema is now retrievable on `Database.schema()` (i.e. graknClient.databases().get("name").schema()` (implemented in client-java). @lriuui0x0 is supposed to implement the feature in console to do `database <name> schema`.

**Comment by haikalpribadi** [comment]
FYI https://github.com/graknlabs/console/issues/140

**Comment by flyingsilverfin** [comment]
ok - have we updated docs?

**Comment by haikalpribadi** [comment]
not yet, but it needs to happen before we release grakn-core
