### ISSUE TITLE
Unable to create system terminal, creating dumb terminal

### ISSUE THREAD

**Issue by nicolamassarenti** [vaticle/typedb-console#152]
Hi,

We are currently experiencing an issue with the console on a machine with Windows 10.

As you can see, `java 11` has been installed as stated in the requirements:
![3](https://user-images.githubusercontent.com/38035878/116520175-a9c83180-a8d2-11eb-9c19-a68bf9ab01cc.png)

We are indeed able to start the server:
![1](https://user-images.githubusercontent.com/38035878/116520215-b51b5d00-a8d2-11eb-8a0f-fc605df6a68d.PNG)

But when we run the command `./grakn console` we receive the following output:
![2](https://user-images.githubusercontent.com/38035878/116520251-c49aa600-a8d2-11eb-8286-1f1a23d18648.png)

**Why do we have this error? How can we solve this?**

In addition, when we try to run a query on Grakn Workbase, we get the error:
![workbase](https://user-images.githubusercontent.com/38035878/116520348-e431ce80-a8d2-11eb-872b-693b5ad93f85.png)
With the server stack trace:
![wokbase-server](https://user-images.githubusercontent.com/38035878/116520420-fdd31600-a8d2-11eb-9347-66304847a8fd.png)

**Could this be related to the console issue?**

Thanks.
Best regards,
Nicola

**Comment by lolski** [comment]
It says "protobuf has invalid UTF-8". Are you performing queries with non-UTF-8 characters? I can't quite clearly see from your screenshot (you may want to increase the quality).

Can you try on the latest TypeDB (aka Grakn) 2.0.2 and Workbase 2.0.2

**Comment by nicolamassarenti** [comment]
Hi @lolski, 

thank you for the answer and sorry for the images, I didn't notice that the quality was so bad! The screenshots are:

1. **Java version 11**
<img width="469" alt="Immagine 2021-04-29 100355" src="https://user-images.githubusercontent.com/38035878/116535175-b86b1480-a8e3-11eb-8a0f-9323b6e02b02.png">

2. **Grakn server up and running** - version `2.0.1`
<img width="945" alt="Immagine 2021-04-29 095956" src="https://user-images.githubusercontent.com/38035878/116535348-f49e7500-a8e3-11eb-9af4-c4600edf2ee7.png">

3. **Grakn console with Warning**
<img width="821" alt="Immagine 2021-04-29 100036" src="https://user-images.githubusercontent.com/38035878/116535508-18fa5180-a8e4-11eb-888e-84e890af2c91.png">

4. **Grakn Workbase error and traceback on Grakn Server** - Grakn Worbase version is `2.0.2`
<img width="953" alt="Immagine 2021-04-29 100716" src="https://user-images.githubusercontent.com/38035878/116535567-2ca5b800-a8e4-11eb-84e0-c2d9f03a8238.png">
<img width="949" alt="Immagine 2021-04-29 100831" src="https://user-images.githubusercontent.com/38035878/116535575-2e6f7b80-a8e4-11eb-875e-9184febcd01c.png">



As you can see, the user reporting this issue is using Grakn `2.0.1`. The Workbase version is `2.0.2`. The characters are all utf-8.


Does the user need to update to Grakn (TypeDB) version `2.0.2` (importing schema and data in the new version) or there exists a solution?

**Comment by lolski** [comment]
> Does the user need to update to Grakn (TypeDB) version 2.0.2 (importing schema and data in the new version) or there exists a solution?

Yes, you should use TypeDB 2.0.2 with Workbase 2.0.2 (see [the compatibility table](http://docs.grakn.ai/docs/workbase/overview#version-compatibility)).

In theory you can download Workbase 2.0.1 but I would recommend upgrading TypeDB since we're moving fast and there are important fixes in each new version.

**Comment by lolski** [comment]
As for the `WARNING: Unable to start system terminal` that gets displayed in `./grakn console`, I think it is just just an indication that `./grakn console` has to perform some "fallback", but it is not fatal and won't cause any issue for you guys.

However we'll still look into that.

**Comment by jamesreprise** [comment]
Unable to reproduce this issue. Additionally, Workbase has been retired.
