### ISSUE TITLE
Bug: console input not buffering on Windows

### ISSUE THREAD

**Issue by LucaCerina** [vaticle/typedb-console#160]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description
Freshly installed on Windows, after starting the server and the console, the input is not enabled and the commands do not run. Pressing Ctrl+C one time shows a new line with the typed keys above

## Environment

1. OS (where TypeDB server runs): Windows 10
2. TypeDB version (and platform): TypeDB 2.1.3
3. TypeDB client: console
4. Other environment details:
- Java version: 14 (OpenJDK)

## Expected Output

Input and commands are correctly buffered and executed

## Actual Output

No input is running.
 
## Additional information
Setting the debug ON in the console configuration shows this
`|-WARN in Logger[io.netty.util.internal.logging.InternalLoggerFactory] - No appenders present in context [default] for logger [io.netty.util.internal.logging.InternalLoggerFactory].`

**Comment by lolski** [comment]
Thank you for reporting the issue! I've moved it to the `typedb-console` repository.

**Comment by vmax** [comment]
@LucaCerina are you testing it using usual Command Prompt (cmd.exe)? Would it change if you tried running on [Windows Terminal](https://github.com/microsoft/terminal)?

**Comment by LucaCerina** [comment]
Yes @vmax I get the same behaviour using cmd, Windows Terminal and "git bash", so my guess it's something at lower level and not the terminal itself.
I am testing it also on Windows Subsystem for Linux

**Comment by LucaCerina** [comment]
Yes, I confirm you that it's running fine on WSL with same OpenJDK version, TypeDB release and Ubuntu 20.04 as OS.

Another additional information is that I have Android Studio 4.2.1 installed on Windows, it could be messing up some Java environment variable

**Comment by jamesreprise** [comment]
Haven't been able to reproduce. Closing.
