### ISSUE TITLE
Error installing typedb-console

### ISSUE THREAD

**Issue by nicolamassarenti** [vaticle/typedb-console#165]
Hi, 

while installing the latest console I ran into this error:

![image](https://user-images.githubusercontent.com/38035878/127835503-ba5c6081-4ac7-4a6c-a705-db20052eb0e6.png)

How can I solve this issue?

**Comment by flyingsilverfin** [comment]
@vmax here's another case of a compressed package looking strange??

**Comment by vmax** [comment]
Fixed in vaticle/typedb-console#168
