### ISSUE TITLE
Comments in script used by --script argument starting the console

### ISSUE THREAD

**Issue by FrankUrbach** [vaticle/typedb-console#170]
In previous versions it was possible to comment scripts. This isn't possible in version 2.3.0

**Comment by lolski** [comment]
Can you elaborate with an example as well as the error when you tried to do so?

**Comment by FrankUrbach** [comment]
eg. :
# To bring this in the database you have to do: typeql console --script=social_network.tql
#create the database

database create social_network
transaction social_network schema write
source social_network_schema.tql
commit
transaction social_network data write
source social_network_data.tql
commit


If you do so, the execution of this file will be terminated.
