### ISSUE TITLE
Windows distribution contains bash script

### ISSUE THREAD

**Issue by BFergerson** [vaticle/typedb-console#28]
Downloaded https://github.com/graknlabs/console/releases/download/1.0.3/grakn-console-windows-1.0.3.zip expecting .bat/.exe files and found a script with a header of `#!/usr/bin/env bash`

**Comment by vmax** [comment]
@BFergerson thank you for reporting! Fixed in #114

As of latest release at the time (2.1.0), Windows distribution correctly contains only the `.bat` file
