### ISSUE TITLE
Could refactor to single deployable artifact.

### ISSUE THREAD

**Issue by adammitchelldev** [vaticle/typedb-console#50]
Currently we deploy `console-distribution` as a separate artifact to various release versions for different platforms. Ideally we can cut this down to a single release distribution package but currently this requires working around the difficult `assemble_targz` macro and there are difficulties with bazel and archive directory structure.

A counter-argument is that since `console-distribution` is not platform specific, it can be thought of as the "base artifact" from which all platform specific artifacts are built.

**Comment by vmax** [comment]
Technically, even though Console (unlike the server) doesn't have any platform-specific code, distributions of Console for different operating systems **are** platform-dependant. For example: Windows distribution only contains `typedb.bat` (CMD); distributions for macOS and Linux contain `typedb` (Bash). Therefore, it makes sense to continue keeping them separate.
